version: '3'

# This file loads the apps and consumes cloud storage resources.


services:

  # loads data from OpenSky Network into S3
  data-load:
    build:
      context: data-load
    image: singlestore-planes-data-load
    environment:
    # TODO: Set variables to your S3 endpoint
    - S3_REGION=us-west-1
    - S3_BUCKET=set_to_your_s3_bucket
    - S3_ACCESSKEY=set_to_your_access_key
    - S3_SECRETKEY=set_to_your_secret_key
    #- S3_FOLDER=set_to_folder_in_bucket_if_any

  # includes both the Express api and Vue app
  webapp:
    build:
      context: .
    image: singlestore-planes-webapp
    ports:
    - 8000:80
    environment:
    # TODO: Set variables to your SingleStore cluster
    - SINGLESTORE_HOST=set_to_client_endpoint
    - SINGLESTORE_USER=admin
    - SINGLESTORE_PASSWORD=set_your_password_here
