version: '3'

# This file loads the apps and consumes cloud storage resources.


services:

  # Adjust /api/.env.docker and /data-load/.env.docker to point to your SingleStore database and AWS S3 buckets

  # loads data from OpenSky Network into S3
  data-load:
    build:
      context: data-load
    image: singlestore-planes-data-load
    environment:
    # TODO: Set variables to your S3 endpoint
    - S3_ENDPOINT=set_to_your_s3_url
    - S3_PORT=443
    - S3_ACCESSKEY=set_to_your_access_key
    - S3_SECRETKEY=set_to_your_secret_key
    - S3_USESSL=true

  # includes both the Express api and Vue app
  webapp:
    build:
      context: .
    image: singlestore-planes-webapp
    ports:
    - 8000:80
    environment:
    # TODO: Set variables to your SingleStore cluster
    - SINGLESTORE_HOST=set_to_client_endpoint
    - SINGLESTORE_USER=admin
    - SINGLESTORE_PASSWORD=set_your_password_here
